services:
  app:
    env_file:
      - .env
    build: .
    ports:
      - "${APP_HOST_PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
  postgres:
    image: postgres:15
    env_file:
      - .env
    # The application drops tables before creating, so no need to 
    # create volumes. If the requirement changes, then uncomment 
    # the following volume definitions.
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
networks:
  app-network:
    driver: bridge
