services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_USER=postgres
      - DB_PASSWORD=T3mp0r4l
      - DB_NAME=tasks
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
